# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ArraySpec": "Data.ipynb",
         "ArraySignal": "Data.ipynb",
         "TensorSpec": "Data.ipynb",
         "TensorSignal": "Data.ipynb",
         "encodes": "Data.ipynb",
         "get_audio_files": "Data.ipynb",
         "audio_extensions": "Data.ipynb",
         "Spectify": "Data.ipynb",
         "AudioLoader": "Data.ipynb",
         "SpecBlock": "Data.ipynb",
         "SignalBlock": "Data.ipynb",
         "Clipper": "Data.ipynb",
         "Invertible1x1Conv": "Layers.ipynb",
         "WeightedConv1d": "Layers.ipynb",
         "WaveNetLayer": "Layers.ipynb",
         "WaveNet": "Layers.ipynb"}

modules = ["data.py",
           "layers.py"]

doc_url = "https://hoftherose.github.io"

git_url = "https://github.com/hoftherose/MiniAudio/tree/master/"

def custom_doc_links(name): return None
