# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"ArraySpec": "Data.ipynb",
         "ArraySignal": "Data.ipynb",
         "TensorSpec": "Data.ipynb",
         "TensorSignal": "Data.ipynb",
         "encodes": "Data.ipynb",
         "get_audio_files": "Data.ipynb",
         "audio_extensions": "Data.ipynb",
         "Spectify": "Data.ipynb",
         "AudioLoader": "Data.ipynb",
         "SpecBlock": "Data.ipynb",
         "SignalBlock": "Data.ipynb",
         "Clipper": "Data.ipynb",
         "Invertible1x1Conv": "Layers.ipynb",
         "WeightedConv1d": "Layers.ipynb",
         "WaveNetLayer": "Layers.ipynb",
         "WaveNet": "Layers.ipynb",
         "conv_block": "Layers.ipynb",
         "up_conv": "Layers.ipynb",
         "U_Net": "Layers.ipynb",
         "Recurrent_block": "Layers.ipynb",
         "RRCNN_block": "Layers.ipynb",
         "R2U_Net": "Layers.ipynb",
         "Attention_block": "Layers.ipynb",
         "AttU_Net": "Layers.ipynb",
         "R2AttU_Net": "Layers.ipynb",
         "NormalizeAudio": "Transforms.ipynb",
         "MuLawEncoding": "Transforms.ipynb",
         "get_pitch": "Transforms.ipynb",
         "frequency_order": "Transforms.ipynb",
         "Stft2d": "Transforms.ipynb"}

modules = ["data.py",
           "layers.py",
           "transforms.py"]

doc_url = "https://hoftherose.github.io"

git_url = "https://github.com/hoftherose/MiniAudio/tree/master/"

def custom_doc_links(name): return None
